Zadaca 2
NikolaPehnec/android-vjestina-tmdb pull request #2
Opened 2022-04-14 21:59 UTC by NikolaPehnec

2022-04-20 09:08 UTC, matejsalkovic requested changes

2022-04-20 09:08 UTC, matejsalkovic commented on app/src/main/java/agency/five/tmdb/MovieCategory.kt
> +    favoriteViewModel: FavoriteMoviesViewModel,
Composable functions that don't represent screens should not know about ViewModel directly, but instead you should pass only state those functions need to render.

2022-04-20 09:08 UTC, matejsalkovic commented on app/src/main/java/agency/five/tmdb/MainActivity.kt
> +        val homeViewModel: HomeViewModel by viewModel()
Move initializations of ViewModels inside screen functions.

2022-04-20 09:08 UTC, matejsalkovic commented on app/src/main/java/agency/five/tmdb/DI/ViewModelModules.kt
> +val ViewModelModules = module {
vals should always start with lowercase

2022-05-09 13:27 UTC, NikolaPehnec commented on app/src/main/java/agency/five/tmdb/FavoriteScreen.kt
> +        .collectAsState(initial = listOf()).value
Not sure if an empty list is a good initial value

2022-05-09 13:30 UTC, NikolaPehnec commented on app/src/main/java/agency/five/tmdb/data/PreviewData.kt
> +class PreviewData {
I returned the previewData class but don't know how to use it in previews considering the fact that composables don't have Lists of data in constructors

2022-05-11 12:51 UTC, matejsalkovic commented on app/src/main/java/agency/five/tmdb/FavoriteScreen.kt
> +        .collectAsState(initial = listOf()).value
It is

2022-05-11 13:05 UTC, matejsalkovic commented on app/src/main/java/agency/five/tmdb/data/PreviewData.kt
> +class PreviewData {
You can use the following pattern:
```
@Composable
fun HomeScreen() {
    // viewModel and state
}

@Composable
fun HomeContent(
    // states and click callbacks
) {
     // implement screen here
}

@Preview
@Composable
fun HomePreview() {
    // call HomeContent with preview data
}
```

2022-05-11 14:36 UTC, NikolaPehnec commented on app/src/main/java/agency/five/tmdb/HomeScreen.kt
> +                    onMovieCardClick = onMovieCardClick,
Not sure how to do that considering the function is called on navController, when calling HomeScreen in NavigationSetup

2022-05-13 07:15 UTC, matejsalkovic approved these changes

2022-05-13 10:51 UTC, merged